In [1]:
import pandas as pd
import numpy as np

# Create sample data
np.random.seed(42)

data = {
    'TransactionID': range(1001, 1011),
    'CustomerID': ['C001', 'C002', 'C003', 'C001', 'C004', 'C005', 'C002', 'C003', 'C006', 'C002'],
    'Merchant': ['Amazon', 'Flipkart', 'Myntra', 'Amazon', 'Zomato', 'Swiggy', 'Flipkart', 'Myntra', 'Amazon', 'Flipkart'],
    'Amount': [1500, 25000, 1200, 1490, 560, 670, 30000, 1100, 900, 40000],
    'Timestamp': pd.date_range(start='2025-07-01 10:00', periods=10, freq='H'),
    'Status': ['Success', 'Success', 'Failed', 'Success', 'Success', 'Failed', 'Success', 'Success', 'Success', 'Success']
}

df = pd.DataFrame(data)
df['IsFraud'] = [0, 1, 0, 0, 0, 0, 1, 0, 0, 1]  # Simulated fraud labels

df

/tmp/ipython-input-1-2437425463.py:12: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  'Timestamp': pd.date_range(start='2025-07-01 10:00', periods=10, freq='H'),

,TransactionID,CustomerID,Merchant,Amount,Timestamp,Status,IsFraud
0,1001,C001,Amazon,1500,2025-07-01 10:00:00,Success,0
1,1002,C002,Flipkart,25000,2025-07-01 11:00:00,Success,1
2,1003,C003,Myntra,1200,2025-07-01 12:00:00,Failed,0
3,1004,C001,Amazon,1490,2025-07-01 13:00:00,Success,0
4,1005,C004,Zomato,560,2025-07-01 14:00:00,Success,0
5,1006,C005,Swiggy,670,2025-07-01 15:00:00,Failed,0
6,1007,C002,Flipkart,30000,2025-07-01 16:00:00,Success,1
7,1008,C003,Myntra,1100,2025-07-01 17:00:00,Success,0
8,1009,C006,Amazon,900,2025-07-01 18:00:00,Success,0
9,1010,C002,Flipkart,40000,2025-07-01 19:00:00,Success,1

In [2]:
# 1 - remove failed transactions
df_clean = df[df['Status'] =='Success']

#reset the index
df_clean = df_clean.reset_index(drop= True)

df_clean

,TransactionID,CustomerID,Merchant,Amount,Timestamp,Status,IsFraud
0,1001,C001,Amazon,1500,2025-07-01 10:00:00,Success,0
1,1002,C002,Flipkart,25000,2025-07-01 11:00:00,Success,1
2,1004,C001,Amazon,1490,2025-07-01 13:00:00,Success,0
3,1005,C004,Zomato,560,2025-07-01 14:00:00,Success,0
4,1007,C002,Flipkart,30000,2025-07-01 16:00:00,Success,1
5,1008,C003,Myntra,1100,2025-07-01 17:00:00,Success,0
6,1009,C006,Amazon,900,2025-07-01 18:00:00,Success,0
7,1010,C002,Flipkart,40000,2025-07-01 19:00:00,Success,1

In [3]:
df_clean.isnull().sum()

TransactionID    0
CustomerID       0
Merchant         0
Amount           0
Timestamp        0
Status           0
IsFraud          0
dtype: int64

In [10]:
# 2 -  Total Spent by Each Customer

total_customer =  df_clean.groupby('CustomerID')['Amount'].sum().reset_index()
total_customer = df_clean.sort_values(by='Amount', ascending=False)

print(total_customer)

total_customer = df_clean.groupby('CustomerID')['Amount'].sum().reset_index()
total_customer = df_clean.sort_values(by='Amount', ascending=False)
print(total_customer)

   TransactionID CustomerID  Merchant  Amount           Timestamp   Status  \
7           1010       C002  Flipkart   40000 2025-07-01 19:00:00  Success
4           1007       C002  Flipkart   30000 2025-07-01 16:00:00  Success
1           1002       C002  Flipkart   25000 2025-07-01 11:00:00  Success
0           1001       C001    Amazon    1500 2025-07-01 10:00:00  Success
2           1004       C001    Amazon    1490 2025-07-01 13:00:00  Success
5           1008       C003    Myntra    1100 2025-07-01 17:00:00  Success
6           1009       C006    Amazon     900 2025-07-01 18:00:00  Success
3           1005       C004    Zomato     560 2025-07-01 14:00:00  Success

   IsFraud        date
7        1  2025-07-01
4        1  2025-07-01
1        1  2025-07-01
0        0  2025-07-01
2        0  2025-07-01
5        0  2025-07-01
6        0  2025-07-01
3        0  2025-07-01
   TransactionID CustomerID  Merchant  Amount           Timestamp   Status  \
7           1010       C002  Flipkart   40000 2025-07-01 19:00:00  Success
4           1007       C002  Flipkart   30000 2025-07-01 16:00:00  Success
1           1002       C002  Flipkart   25000 2025-07-01 11:00:00  Success
0           1001       C001    Amazon    1500 2025-07-01 10:00:00  Success
2           1004       C001    Amazon    1490 2025-07-01 13:00:00  Success
5           1008       C003    Myntra    1100 2025-07-01 17:00:00  Success
6           1009       C006    Amazon     900 2025-07-01 18:00:00  Success
3           1005       C004    Zomato     560 2025-07-01 14:00:00  Success

   IsFraud        date
7        1  2025-07-01
4        1  2025-07-01
1        1  2025-07-01
0        0  2025-07-01
2        0  2025-07-01
5        0  2025-07-01
6        0  2025-07-01
3        0  2025-07-01

In [5]:
#🔍 3 : Average Spend per Merchant
avg_by_merchant = df_clean.groupby('Merchant')['Amount'].mean().reset_index()
avg_by_merchant = avg_by_merchant.sort_values(by='Amount', ascending=False)

print(avg_by_merchant)

   Merchant        Amount
1  Flipkart  31666.666667
0    Amazon   1296.666667
2    Myntra   1100.000000
3    Zomato    560.000000

In [6]:
# 🔍 4 : Highest Single Transaction

highest_txn = df_clean[df_clean['Amount'] == df_clean['Amount'].max()]

print(highest_txn)

   TransactionID CustomerID  Merchant  Amount           Timestamp   Status  \
7           1010       C002  Flipkart   40000 2025-07-01 19:00:00  Success

   IsFraud
7        1

In [7]:
# 🧮 5 : Transaction Count by Merchant

merchant_count = df_clean['Merchant'].value_counts().reset_index()
merchant_count.columns = ['Merchant' ,'TransactionCount']

print(merchant_count)

   Merchant  TransactionCount
0    Amazon                 3
1  Flipkart                 3
2    Zomato                 1
3    Myntra                 1

In [8]:
# 6:  Day-wise Total Spending

df_clean['date'] = df_clean['Timestamp'].dt.date

daywise_spent = df_clean.groupby('date')['Amount'].sum().reset_index()
print(daywise_spent)

         date  Amount
0  2025-07-01  100550

In [11]:
# ⌚ 7 : Hourly Spending Pattern

df_clean['Hour'] = df_clean['Timestamp'].dt.hour

hourly_spend = df_clean.groupby('Hour')['Amount'].sum().reset_index()

print(hourly_spend)

   Hour  Amount
0    10    1500
1    11   25000
2    13    1490
3    14     560
4    16   30000
5    17    1100
6    18     900
7    19   40000

In [13]:
# 🧍 8:   Customer-wise Average Transaction Amount

customer_avg = df_clean.groupby('CustomerID')['Amount'].mean().reset_index()
customer_avg.columns = ['CustomerID', 'AverageAmount']

print(customer_avg)

  CustomerID  AverageAmount
0       C001    1495.000000
1       C002   31666.666667
2       C003    1100.000000
3       C004     560.000000
4       C006     900.000000

In [17]:
#📊 9 : Number of Transactions Above ₹10,000

hightxn = df_clean[df_clean['Amount'] > 10000]

print(hightxn)

print(f"Total High value of transactions : {len(hightxn)}")

   TransactionID CustomerID  Merchant  Amount           Timestamp   Status  \
1           1002       C002  Flipkart   25000 2025-07-01 11:00:00  Success
4           1007       C002  Flipkart   30000 2025-07-01 16:00:00  Success
7           1010       C002  Flipkart   40000 2025-07-01 19:00:00  Success

   IsFraud        date  Hour
1        1  2025-07-01    11
4        1  2025-07-01    16
7        1  2025-07-01    19
Total High value of transactions : 3

In [18]:
# 10:  Fraud Rate by Merchant

fraud_rate = df_clean.groupby('Merchant')['IsFraud'].mean().reset_index()
fraud_rate.columns = ['Merchant', 'FraudRate']
fraud_rate = fraud_rate.sort_values(by='FraudRate', ascending=False)
print(fraud_rate)

   Merchant  FraudRate
1  Flipkart        1.0
0    Amazon        0.0
2    Myntra        0.0
3    Zomato        0.0

In [19]:
# 11 : Total Amount Lost to Fraud

fraud_amount = df_clean[df_clean['IsFraud'] == 1]['Amount'].sum()

print(f"Total ₹ Lost in Fraud: {fraud_amount}")

Total ₹ Lost in Fraud: 95000

In [20]:
# 🛠️ 12 : Add a New Column: GST 18% Charged

df_clean['GST_18%'] = df_clean['Amount'] * 0.18

print(df_clean[['TransactionID','Amount','GST_18%']])

   TransactionID  Amount  GST_18%
0           1001    1500    270.0
1           1002   25000   4500.0
2           1004    1490    268.2
3           1005     560    100.8
4           1007   30000   5400.0
5           1008    1100    198.0
6           1009     900    162.0
7           1010   40000   7200.0

In [21]:
# 🔄 13 :  Normalize Amount Column

df_clean['NormalizedAmount'] = (df_clean['Amount'] - df_clean['Amount'].mean())

print(df_clean[['Amount', 'NormalizedAmount']])

   Amount  NormalizedAmount
0    1500         -11068.75
1   25000          12431.25
2    1490         -11078.75
3     560         -12008.75
4   30000          17431.25
5    1100         -11468.75
6     900         -11668.75
7   40000          27431.25

In [22]:
# 💱 14:  Convert ₹ to USD (₹1 = $0.012)

df_clean['Amount_USD'] = df_clean['Amount'] * 0.012

print(df_clean[['TransactionID','Amount','Amount_USD']])

   TransactionID  Amount  Amount_USD
0           1001    1500       18.00
1           1002   25000      300.00
2           1004    1490       17.88
3           1005     560        6.72
4           1007   30000      360.00
5           1008    1100       13.20
6           1009     900       10.80
7           1010   40000      480.00

In [23]:
# 15 :  Fraud by Customer — Who is most vulnerable?

fraud_by_customer =  df_clean[df_clean['IsFraud'] ==1].groupby('CustomerID').size().reset_index()

print(fraud_by_customer)

  CustomerID  0
0       C002  3